name: Deploy to Production
on: push

concurrency: # Set concurrency group for the entire workflow
  group: production_deploy_lock
jobs:
 test:
    runs-on: ubuntu-latest
    steps:
    - name: echo github
      run: echo '${{ github }}'
 
